elevator_controller:
    type:  elevator_controller/ElevatorController
    lift: ["lift_joint", "lift_follower1_joint", "lift_follower2_joint"]
    intake1: "intake1_joint"
    intake2: "intake2_joint"
    pivot: "pivot_joint"
    
    intake_power_diff_multiplier: 1
    arm_length: 0.4318 
    max_extension: 2.03 #3.628571429 #29619 
    climb_height: 1.3 
    min_extension: 0.41 

    
    limit_power_press: .08   

    custom_f_lift_high: 153.45 #Fix  
    custom_f_lift_low: 53.45   #Fix  

    custom_f_arm_mass: 153.45 #Fix  
    custom_f_arm_fric: 53.45   #Fix  

    after_shift_max_accel: 2 #fix
    after_shift_max_vel: .5 #fix

    hook_depth: 0.274706  #FIX
    hook_min_height: 1.20 #FIX
    hook_max_height: 1.45 #FIX
 
    climb_cur_lim: 60
    norm_cur_lim: 15

    drop_down_pos: .2 #FIX
    drop_down_tolerance: .1 #FIX
    safe_to_go_back_y: 1.95 #FIX
    cut_off_x_line: .17 #FIX
    cut_off_y_line: .7 #FIX

    dist_to_front_cube: .371 #fix this 
    dist_to_front_clamp: .075

    ready_to_go_into_intake_with_cube_x: .365

    ready_to_go_into_intake_with_cube_y: .6
    top_intake_cut_off_line_for_put_in_intake: 0.47

    
    #Fix below remove poly points
    #right now, over the back is disabled 
    polygon_points_down: [-2.0, -1.0, -2.0, 3.0, .17, 3.0, .17, 0.7, 0.17, 0.7, 0.17, 0.32, 1.0, 0.32, 1.0, -1.1, -2.0, -1.0] #~5 cm of clearance  #consider widening zone of over back a little 
    polygon_points_up: [-2.0, -1.0, -2.0, 3.0, -0.31, 3.0, -0.31, -1.0, 0.0, -1.0, 0.0, 2.3818, .17, 2.2818, .17, 0.7, 1.0, .7, 1.0, -1.5, -2.0, -1.5, -2.0, -1.0] #~5 cm of clearance  #consider widening zone of over back a little 
    
    polygon_points_intake_up: [-2.0, 0.7, 1.0, 0.7, 1.0, 0.0, -2.0, 0.0, -2.0, 0.7] #[-2.0, 0.6, 0.225, 0.6, 0.225, 0.0, -2.0, 0.0, -2.0, 0.6]
    polygon_points_intake_down: [-2.0, -1.0, -2.1, -1.0, -2.1, -1.1, -2.0, -1.0] #Currently removing nothing #[-2.0, 0.4, 1.0, 0.4, 1.0, 0.0, -2.0, 0.0, -2.0, 0.4] 
    polygon_points_intake_in_transition: [-2.0, 0.7, 1.0, 0.7, 1.0, 0.0, -2.0, 0.0, -2.0, 0.7] 

    #Up and in transition both take out the entire bottom quadrant

    lift_joint:
        joint: lift
        close_loop_values:
            - {p: .4, i: 0.0005, d: 0.2, f: 0.1669, i_zone: 750, closed_loop_peak_output: .5} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
            - {p: .5, i: 0.0005, d: 7.5, f: 0.0235389351901052, i_zone: 750, closed_loop_peak_output: 1.0} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500} 
        invert_output: True
        sensor_phase: True
        feedback_type: CTRE_MagEncoder_Absolute
        conversion_factor: 0.0454676
        motion_cruise_velocity: 2.75 
        motion_acceleration: 4
        current_limit_continuous_amps: 15
        current_limit_enable: True
    lift_follower1_joint:
        joint: lift_follower1 
        invert_output: True
        current_limit_continuous_amps: 60
        current_limit_enable: True
    lift_follower2_joint:
        joint: lift_follower2
        invert_output: True
        current_limit_continuous_amps: 60
        current_limit_enable: True
    pivot_joint:
        type: talon_controllers/TalonMotionMagicCloseLoopController
        joint: pivot
        feedback_type: CTRE_MagEncoder_Absolute
        close_loop_values:
            - {p: 2, i: 0.0005, d: 0.25, f: 7, i_zone: 300, allowable_closed_loop_error: 40} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
            - {p: 2, i: 0.005, d: 0.25, f: 7, i_zone: 300, allowable_closed_loop_error: 40} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
        invert_output: True
        sensor_phase: False
        peak_output_forward: 1.0
        peak_output_reverse: -1.0
        nominal_output_forward: 0.0
        nominal_output_reverse: 0.0
        motion_cruise_velocity: 1.5
        #limit_switch_local_reverse_normal: "NormallyOpen"
        #limit_switch_local_reverse_source: "FeedbackConnector"
        motion_acceleration: 2
        voltage_compensation_enable: true
        softlimit_reverse_threshold: 0
        softlimit_forward_threshold: 1
        conversion_factor: 1 #FIX
        current_limit_continuous_amps: 35
        current_limit_enable: True
        closed_loop_ramp: .1
    intake1_joint:
        joint: intake1
        invert_output: True
        sensor_phase: False
        current_limit_continuous_amps: 40
        current_limit_enable: True
    intake2_joint:
        joint: intake2
        invert_output: False
        sensor_phase: True
        current_limit_continuous_amps: 40
        current_limit_enable: True
