#For 2018 comp bot
swerve_drive_controller:
    steering_joint_fl: 
        offset: 2.2073983537674375
    steering_joint_fr: 
        offset: 0.0582912699396544
    steering_joint_bl: 
        offset: -6.79860285190916
    steering_joint_br: 
        offset: 2.16137893013087
