teleop_params:
    high_scale_config_x: .36
    high_scale_config_y: 2.27
    high_scale_config_up_or_down: true
    mid_scale_config_x: .36
    mid_scale_config_y: 2.06
    mid_scale_config_up_or_down: true
    
    #low scale currently not used
    low_scale_config_x: .36
    low_scale_config_y: 1.83
    low_scale_config_up_or_down: true
    switch_config_x: .425
    switch_config_y: 1.2
    switch_config_up_or_down: true
    #exchange should probably be the same as intake
    exchange_config_x: .24
    exchange_config_y: .433 #check this
    exchange_config_up_or_down: false
    intake_ready_to_drop_x: .18
    intake_ready_to_drop_y: 0.5 #1.075 - y pos arm relative

    intake_ready_to_drop_up_or_down: false
    intake_high_x: .18
    intake_high_y: .43
    
    drop_x_tolerance: .1


    intake_high_up_or_down: false
    intake_low_x: .18
    intake_low_y: .376
    




    intake_low_up_or_down: false
    climb: 0.83
    move_out_pos_x: -0.35
    move_out_pos_y: 0.6
    move_out_up_or_down: true
    move_out_down_y: -1.0 
    default_x: .35
    default_y: 1.0
    default_up_or_down: true
    high_return_intake_x: .1 
    high_return_intake_y: 1
    high_return_intake_up_or_down: true
    timeout: 15
    exchange_delay: 0.5
    intake_power: 0.8
    intake_hold_power: 0.3
    wait_after_clamp: 0.4
    wait_after_open: 0.2
    wait_open_before_drop: 0.5
    delay_after_move_intake: 1.0
    wait_for_match_data: 2.0
    num_cmd_vel_modes: 10 #fix

    over_back_x: -0.3
    over_back_y: 2.33
    over_back_up_or_down: true
    
    wait_stabilize_before_drop: 0.0
