elevator_controller:
    type:   elevator_controller/ElevatorController

    elevator_joint: [ 'elevator_master', 'elevator_follower1', 'elevator_follower2', 'elevator_follower3' ]

    arb_feed_forward_up: 0.0

    # How quickly the elevator moves down when zeroing itself
    elevator_zeroing_percent_output: -0.1 # TODO : tune me

    # If there are no negative velocity readings while zeroing
    # for this amount of time, assume the elevator is stuck
    # or has hit bottom and the limit switch is broken.  Stop
    # trying to drive down to prevent killing the motor
    elevator_zeroing_timeout:  2.0
    elevator_master: 
        type: talon_controllers/TalonControllerInterface 
        joint: elevator_master
        close_loop_values:
            - {p: 1, i: 0.0, d: 0, f: 1.5, i_zone: 0, closed_loop_peak_output: 1.0}

        # TODO : tuning
        # motion_cruise_velocity: 32
        # motion_acceleration: 150
              
        sensor_phase: True 
        invert_output: False

        feedback_type: CTRE_MagEncoder_Absolute

        # TODO : bottom limit switch config
        # limit_switch_local_forward_source: FeebackConnector
        # limit_switch_local_forward_normal: NormallyOpen

        # TODO : figure out what value this should be
        # Only need one direction, to
        # prevent the elevator from running off the top
        softlimit_forward_threshold: 10.0
        softlimit_forward_enable: True

        voltage_compensation_enable: True
        voltage_compensation_saturation: 12.5

        # TODO : used to convert encoder position from radians to meters
        # .0573 ... divide or multiply?
        conversion_factor: 0.02959

    elevator_follower1: 
        joint: elevator_follower1

    elevator_follower2: 
        joint: elevator_follower2

    elevator_follower3: 
        joint: elevator_follower3
