elevator_controller:
    type:   elevator_controller/ElevatorController

    elevator_joint: [ 'elevator_master', 'elevator_follower1', 'elevator_follower2', 'elevator_follower3' ]

    arb_feed_forward_up: 0.0

    # How quickly the elevator moves down when zeroing itself
    elevator_zeroing_percent_output: -0.2 # TODO : tune me

    # If there are no negative velocity readings while zeroing
    # for this amount of time, assume the elevator is stuck
    # or has hit bottom and the limit switch is broken.  Stop
    # trying to drive down to prevent killing the motor
    elevator_zeroing_timeout:  2.0

    slow_peak_output: 0.3 #Absolute value of max percent output if the elevator controller is told to go slow in the service request, useful for climbing

    elevator_master: 
        type: talon_controllers/TalonControllerInterface 
        joint: elevator_master
        close_loop_values:
            - {p: 0.3, i: 0.0, d: 0, f: 0.0, i_zone: 0, closed_loop_peak_output: 1.0}
            - {p: 0.22, i: 0.0, d: 0, f: 0.0, i_zone: 0, closed_loop_peak_output: 1.0}

        # TODO : tuning
        motion_cruise_velocity: 1.5
        motion_acceleration: 6
              
        sensor_phase: True 
        invert_output: False

        feedback_type: CTRE_MagEncoder_Relative

        # TODO : bottom limit switch config
        limit_switch_local_reverse_source: "FeedbackConnector"
        limit_switch_local_reverse_normal: "NormallyOpen"

        # TODO : figure out what value this should be
        # Only need one direction, to
        # prevent the elevator from running off the top
        softlimit_forward_threshold: 1.5 #1.66755
        softlimit_forward_enable: True

        voltage_compensation_enable: True
        voltage_compensation_saturation: 12.5

        # TODO : used to convert encoder position from radians to meters
        # .0573 ... divide or multiply?
        conversion_factor: 0.02959

        dynamic_reconfigure: true

    elevator_follower1: 
        joint: elevator_follower1
        invert_output: False

    elevator_follower2: 
        joint: elevator_follower2
        invert_output: True

    elevator_follower3: 
        joint: elevator_follower3
        invert_output: True
