elevator_controller:
    type:   elevator_controller/ElevatorController
    elevator_joint: "elevator"

    arb_feed_forward_up: 0.0

    # How quickly the elevator moves down when zeroing itself
    elevator_zeroing_percent_output: -0.1 # TODO : tune me

    # TODO : figure this out. It will be the reading in radians 
    # from the top to the bottom of the elevator, plus some margin
    # for error
    elevator_sensor_bad_distance: -20.0
    elevator: 
        type: talon_controllers/TalonControllerInterface 
        joint: elevator_joint
        close_loop_values:
            - {p: 1, i: 0.0, d: 0, f: 1.5, i_zone: 0, closed_loop_peak_output: 1.0}
        feedback_type: CTRE_MagEncoder_Absolute

        # TODO : bottom limit switch config
        # limit_switch_local_forward_source: FeebackConnector
        # limit_switch_local_forward_normal: NormallyOpen

        # TODO : figure out what value this should be
        # Only need one direction, to
        # prevent the elevator from running off the top
        softlimit_forward_threshold: 10.0
        softlimit_forward_enable: True
