align_cargo_params: #params defined in align_server_cpp #default values
    align_timeout: 4
    x_timeout: 3
    y_timeout: 3
    orient_timeout: 2
    x_error_threshold: 0.07
    y_error_threshold: 0.05
    orient_error_threshold: 0.1
align_hatch_params:
    align_timeout: 4
    x_timeout: 3
    y_timeout: 3
    orient_timeout: 2
    x_error_threshold: 0.02
    y_error_threshold: 0.02
    orient_error_threshold: 0.1
align_with_terabee_params: #params defined in align_with_terabee.cpp
    cmd_vel_to_pub: 0.7
    distance_bound: 0.07 
    distance_target: 0.12
    cargo_pid_max_distance: 0.5
    adjust_terabee_dists: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
align_with_camera_params: 
    cmd_vel_to_pub: 0.7
    error_threshold: 0.1
align_server_topics:
    align_cargo_rocketship:
        enable_x_pub: "hatch_panel_distance_pid/pid_enable"
        x_error_topic: "hatch_panel_distance_pid/pid_debug"
orient_pid:
    p0: 13.0
    i0: 0.0
    d0: 0.0
    p1: 1.25
    i1: 0.5
    d1: 0.0
#change these values for debugging auto align
do_orient: true
track_target: false #If true doesn't actually align!!!!
do_pid: true
hold_orient: True 
constant_vel: -0.6
do_align: true
after_orient_delay: 1

minimum_x_for_any_pub: 0.2
minimum_y_for_nonzero_pub: 0.02
minimum_x_for_nonzero_pub: 0.5
