align_server_params:
    align_timeout: 10
    orient_timeout: 2
    x_error_threshold: 0.05
    cargo_error_threshold: 0.05
    orient_error_threshold: 0.05
align_with_terabee_params:
    cmd_vel_to_pub: 0.6
    distance_bound: 0.04
    distance_target: 0.15
    cargo_pid_max_distance: 0.5
