actionlib_lift_params:
    cargo:
        intake_position: 0.0
        cargo_ship_position: 0.427 # TODO fix me
        rocket1_position: 0.427260696617
        rocket2_position: 1.07003544694
        rocket3_position: 1.65
    hatch:
        intake_position: 0.0
        cargo_ship_position: 0.0
        rocket1_position: 0.0
        rocket2_position: 0.72
        rocket3_position: 1.46257241755 
    climber:
        deploy_position: 0.0
        climb_position: 0.0
        climb_low_position: 0.0
        deploy_timeout: 5.0
        climb_timeout: 15.0
        climb_low_timeout: 10.0
        running_forward_timeout: 2.0
    max_speed: -1.0
    timeout: 10
    elevator_position_deadzone: 0.05
    collision_range_min: 0.01
    collision_range_max: 0.5
    carriage_height: 0.1

