actionlib_hatch_panel_outtake_params:
    elevator_timeout: 0 #in seconds
    pause_time_after_extend: 0.25 #time to pause between piston actuations, in seconds
    pause_time_after_release: 0.25 #time to pause between piston actuations, in seconds

