topics:
-
  name    : pid
  topic   : /navX_snap_to_goal_pid/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : teleop joystick comp
  topic   : /teleop/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 200
-
  name    : terabee aligning 
  topic   : /align_with_terabee/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : climber server
  topic   : /climber/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 150
