#topics:
#-
#  name    : navigation
#  topic   : nav_vel
#  timeout : 0.5
#  priority: 10
#-
#  name    : joystick
#  topic   : joy_vel
#  timeout : 0.5
#  priority: 100
#-
#  name    : keyboard
#  topic   : key_vel
#  timeout : 0.5
#  priority: 90
#-
#  name    : tablet
#  topic   : tab_vel
#  timeout : 0.5
#  priority: 100

topics:
-
  name    : pid
  topic   : /navX_snap_to_goal_pid/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : teleop joystick comp
  topic   : /teleop/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 200
-
  name    : terabee aligning 
  topic   : /align_with_terabee/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : climber server
  topic   : /climber/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 150
