topics:
-
  name    : pid_navX
  topic   : /align_server/navX/pid/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : teleop joystick comp
  topic   : /teleop/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 200
-
  name    : climber server
  topic   : /climber/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 150
-
  name    : pid_terabee
  topic   : /align_server/terabee/pid/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : pid_server
  topic   : /align_server/server/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100

locks: []
