topic:
-
  name    : pid
  topic   : /frcrobot_jetson/publish_pid_cmd_vel/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : teleop joystick comp
  topic   : /frcrobot_jetson/teleop_joystick_comp/cmd_vel
  timeout : 0.2
  priority: 200
-
  name    : terabee aligning 
  topic   : /frcrobot_jetson/align_with_terabee/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : climber server
  topic   : /frcrobot_jetson/climber_server/cmd_vel
  timeout : 0.2
  priority: 150
