topics:
-
  name    : align_pid
  topic   : /align_server/align_pid/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : teleop joystick comp
  topic   : /teleop/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 200
-
  name    : climber server
  topic   : /climber/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 150
-
  name    : outtake_hatch_panel_server
  topic   : /hatch_outtake/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
locks: []
